#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase
rm -rf constant/*/polyMesh
rm -rf constant/polyMesh 
rm -rf 0/heater
rm -rf 0/water
